version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 20
  webapi:
    build:
      context: ./src
      dockerfile: webapi-dockerfile
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DevContainer
