version: "3.6"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9411/zipkin/"
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:15672"
      interval: 5s
      timeout: 5s
      retries: 5
  service:
    build:
      context: ./src
      dockerfile: service-dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    links: 
      - rabbitmq
      - zipkin
    environment:
      - ASPNETCORE_ENVIRONMENT=DevContainer
  webapi:
    build:
      context: ./src
      dockerfile: webapi-dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    links: 
      - rabbitmq
      - zipkin
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DevContainer
